####################
## Train
####################
train:
  add_time_channels: False # Add time channels to the data (year, day of year)
  dst:
    data_url: null
    #data_url: 'https://sol.spacenvironment.net/jb2008/indices/DSTFILE.TXT'
    data_path: '../data/output.txt'
  horizon: 144 # 6 days * 24 values per day
  lookback: 432 #  3*horizon
  partial_n: 
    - 0.01
    - 0.01

####################
## Eval
####################
eval:
  # Path to learner wandb artifact to load (project/entity/run/artifact:version)
  # If null, the learner in the local tmp folder will be used
  learner_artifact: null
