####################
## Data
####################
data:
  force_download: False
  data_path: '../data/DST_IAGA2002.txt'
  data_nb: "./geodst_data.ipynb"
  df_save_path: "./preprocessed_data/dataframes/geodst.pkl"
  preproc_pipe_save_path: "./preprocessed_data/pipelines/preproc_geodst.pkl"

####################
## Train
####################
train:
  add_time_channels: False # Add time channels to the data (year, day of year)
  horizon: 144 # default: 6 days * 24 values per day (144)
  lookback: 432 #  default = 3*horizon
  partial_n: 0.001
  
####################
## Eval
####################
eval:
  dst_data_path: '../data/DST_IAGA2002.txt' # SAME USED TO TRAIN THE LEARNER!
  # Path to learner wandb artifact to load (project/entity/run/artifact:version)
  # If null, the learner in the local tmp folder will be used
  learner_artifact: null
  round_preds: True # Round predictions to the nearest integer
  # Path to the F10.7 data
  solfsmy_data_path: '../data/SOLFSMY.TXT'