####################
## Train
####################
train:
  add_time_channels: False # Add time channels to the data (year, day of year)
  solap:
    data_url: 'https://www-app3.gfz-potsdam.de/kp_index/Kp_ap_since_1932.txt'
    data_path: '../data/SOLAP.TXT'
  horizon: 48 # default: 6 days * 8 values per day
  lookback: 144 #  default = 3*horizon
  partial_n: 0.001

####################
## Eval
####################
eval:
  solap_data_path: '../data/SOLAP.TXT' # SAME USED TO TRAIN THE LEARNER!
  # Path to learner wandb artifact to load (project/entity/run/artifact:version)
  # If null, the learner in the local tmp folder will be used
  learner_artifact: null
  round_preds: True # Round predictions to the nearest integer
  # Path to the F10.7 data
  solfsmy_data_path: '../data/SOLFSMY.TXT'
  timestep: 3 # Data points every 3 hours
