####################
## Train
####################
train:
  add_time_channels: False # Add time channels to the data (year, day of year)
  data_columns_fcst: # Columns to use for forecasting
    - F10
    - S10
    - M10
    - Y10
  data_path: '../data/SOLFSMY.TXT'
  bs: 32
  lookback: 8
  horizon: 6

####################
## Eval
####################
eval:
  solfsmy_data_path: '../data/SOLFSMY.TXT'
  
####################
## F10.7 Historical Values
####################
data:
  dataF107_url: 'https://www.ngdc.noaa.gov/stp/space-weather/solar-data/solar-features/solar-radio/noontime-flux/penticton/penticton_adjusted/listings/listing_drao_noontime-flux-adjusted_daily.txt'
  dataF107_path: '../data/SOLF107_HistoricalValues.txt' 