####################
## Train
####################
train:
  add_time_channels: False # Add time channels to the data (year, day of year)
  data_columns_fcst: # Columns to use for forecasting
    - F10
    - S10
    - M10
    - Y10
  data_url: 'https://sol.spacenvironment.net/jb2008/indices/SOLFSMY.TXT'
  data_path: '../data/SOLFSMY.TXT'
  bs: 32

####################
## Eval
####################
eval:
  # Path to learner wandb artifact to load (project/entity/run/artifact:version)
  # If null, the learner in the local tmp folder will be used
  learner_artifact: "vrodriguezf90/swdf/solfsmy:latest"
