####################
## Data
####################
data:
  data_url: 'https://sol.spacenvironment.net/JB2008/indices/SOLFSMY.TXT'
  data_path: '../data/SOLFSMY.TXT'
  force_download: False
  data_nb: "./solfsmy_data.ipynb"
  df_save_path: "./preprocessed_data/dataframes/solfsmy.pkl"
  preproc_pipe_save_path: "./preprocessed_data/pipelines/preproc_solfsmy.pkl"
  data_columns: 
    - F10
    - S10
    - M10
    - Y10
  data_time_columns:
    - Year
    - DDD
  add_time_channels: False # Add time channels to the data (year, day of year)

  

####################
## Train
####################
train:
  bs: 32

####################
## Eval
####################
eval:
  # Path to learner wandb artifact to load (project/entity/run/artifact:version)
  # If null, the learner in the local tmp folder will be used
  # learner_artifact: "vrodriguezf90/swdf/solfsmy:latest"
  dst_data_path: '../data/DST_IAGA2002.txt' # SAME USED TO TRAIN THE LEARNER!
  # Path to learner wandb artifact to load (project/entity/run/artifact:version)
  # If null, the learner in the local tmp folder will be used
  learner_artifact: null
  round_preds: True # Round predictions to the nearest integer
  # Path to the F10.7 data
  solfsmy_data_path: '../data/SOLFSMY.TXT'