add_time_channels: False # Add time channels to the data (year, day of year)
arch_name: "MiniRocketPlus" # See `all_arch_names` in tsasi
bs: 16 # Batch size
data_columns_fcst: # Columns to use for forecasting
  - F10
  - S10
  - M10
  - Y10
data_url: 'https://sol.spacenvironment.net/jb2008/indices/SOLFSMY.TXT'
data_path: '../data/SOLFSMY.TXT'
horizon: 6 # same as paper by Licata et al. (2020)
init_weights: True  # Kaiming init weights
lookback: 36 
lr_max: null # Maximum learning rate. If none, it will be computed with fastai's LRFinder
n_epoch: 5 # Number of epochs to train for
partial_n: null # null uses all training set, float in [0,1] uses a percentage, list filters valid too
use_wandb: False # To use it, the environment variable WANDB_API_KEY must be set
wandb_group: null # Useful to group runs that belong to the same optuna study
wandb_mode: 'offline' # 'online' or 'offline' for wandb
wandb_project: 'swdf' # Name of wandb project